title: "تجربه من از بوتکمپ هم مسیر نشان"
description: "احتمالا با خواندن این متن تجربه یا حتی ورود به بوتکمپ برای شما راحت تر شود"
theme: minima
url: "https://rahmasir.github.io/"
lang: fa
minima:
  skin: auto